server:
  port: 8502
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/movies?currentSchema=public
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
